contentful/vault

- core/src/main/java/com/contentful/vault/LinkResolver.java
- tests-integration/src/test/java/com/contentful/vaultintegration/ArrayTest.java
> Fix link resolution for arrays of resources

- core/src/main/java/com/contentful/vault/Vault.java
> Provide direct, read-only access to the database

- core/src/main/java/com/contentful/vault/SyncConfig.java
- core/src/main/java/com/contentful/vault/SyncRunnable.java
- tests-integration/src/test/java/com/contentful/vaultintegration/SyncTest.java
> Support forcing initial sync

- core/src/main/java/com/contentful/vault/LinkResolver.java
- core/src/main/java/com/contentful/vault/SyncRunnable.java
- pom.xml
- tests-integration/pom.xml
- tests-integration/src/test/java/com/contentful/vaultintegration/ArrayTest.java
- tests-integration/src/test/java/com/contentful/vaultintegration/BaseTest.java
- tests-integration/src/test/resources/vault_initial.json
> Use empty collections for empty arrays/maps

- .travis.yml
- circle.yml
Use Circle CI for tests and Travis for snapshots deployment.
> Setup Circle CI

- core/src/main/java/com/contentful/vault/Link.java
- core/src/main/java/com/contentful/vault/LinkResolver.java
- core/src/main/java/com/contentful/vault/Query.java
- core/src/main/java/com/contentful/vault/SpaceHelper.java
- core/src/main/java/com/contentful/vault/SyncRunnable.java
- tests-integration/src/test/java/com/contentful/vaultintegration/LinksTest.java
- tests-integration/src/test/java/com/contentful/vaultintegration/lib/links/AssetsContainer.java
- tests-integration/src/test/java/com/contentful/vaultintegration/lib/links/LinksSpace.java
- tests-integration/src/test/resources/links_initial.json
- tests-integration/src/test/resources/links_space.json
- tests-integration/src/test/resources/links_update.json
> Fix persistence and resolution of links

- core/src/main/java/com/contentful/vault/Asset.java
- core/src/main/java/com/contentful/vault/Resource.java
> Resource equals & hashCode

- README.md
- proguard-vault.cfg
> Add ProGuard config file

- compiler/src/main/java/com/contentful/vault/compiler/ModelInjection.java
- compiler/src/main/java/com/contentful/vault/compiler/SpaceInjection.java
- compiler/src/test/resources/ModelInjection.java
- compiler/src/test/resources/SpaceInjection.java
- compiler/src/test/resources/SpaceInjectionVersion.java
- core/src/main/java/com/contentful/vault/LinkResolver.java
- core/src/main/java/com/contentful/vault/Query.java
- core/src/main/java/com/contentful/vault/SpaceHelper.java
- core/src/main/java/com/contentful/vault/SyncException.java
- core/src/main/java/com/contentful/vault/SyncRunnable.java
- pom.xml
- tests-integration/src/test/java/com/contentful/vaultintegration/AllTheThingsTest.java
- tests-integration/src/test/java/com/contentful/vaultintegration/BlobTest.java
+ suppress unchecked warnings from generated code.
> Fix raw types

- CHANGELOG.md
- core/pom.xml
- core/src/main/java/com/contentful/vault/AbsQuery.java
- core/src/main/java/com/contentful/vault/FetchQuery.java
- core/src/main/java/com/contentful/vault/LinkResolver.java
- core/src/main/java/com/contentful/vault/ObserveQuery.java
- core/src/main/java/com/contentful/vault/QueryResolver.java
- core/src/main/java/com/contentful/vault/Vault.java
- core/src/test/java/com/contentful/vault/ObserveTest.java
- pom.xml
- tests-integration/src/test/java/com/contentful/vaultintegration/ObserveTest.java
> Support queries with RxJava

- CHANGELOG.md
- core/src/main/java/com/contentful/vault/SyncResult.java
- core/src/main/java/com/contentful/vault/SyncRunnable.java
- core/src/main/java/com/contentful/vault/Vault.java
- tests-integration/src/test/java/com/contentful/vaultintegration/BaseTest.java
- tests-integration/src/test/java/com/contentful/vaultintegration/ObserveTest.java
> Support observing sync results with RxJava

- CHANGELOG.md
- compiler/src/main/java/com/contentful/vault/compiler/Processor.java
- compiler/src/test/java/com/contentful/vault/compiler/FieldTest.java
> Fail for static @Field elements

- CHANGELOG.md
- compiler/src/main/java/com/contentful/vault/compiler/Processor.java
- compiler/src/test/java/com/contentful/vault/compiler/FieldTest.java
> Fail for private @Field elements

- CHANGELOG.md
- README.md
- core/src/main/java/com/contentful/vault/Vault.java
> Add simplified `requestSync(CDAClient)` extension

- CHANGELOG.md
- core/src/main/java/com/contentful/vault/SqliteHelper.java
- tests-integration/src/test/java/com/contentful/vaultintegration/UpgradeTest.java
> Fix failure on db upgrades

- CHANGELOG.md
- pom.xml
> Use contentful.java v5.0.1

- CHANGELOG.md
- core/src/main/java/com/contentful/vault/SyncRunnable.java
- tests-integration/src/test/java/com/contentful/vaultintegration/LocalizedLinksTest.java
- tests-integration/src/test/java/com/contentful/vaultintegration/lib/localizedlinks/Container.java
- tests-integration/src/test/java/com/contentful/vaultintegration/lib/localizedlinks/LocalizedLinksSpace.java
- tests-integration/src/test/resources/localizedlinks/initial.json
- tests-integration/src/test/resources/localizedlinks/space.json
- tests-integration/src/test/resources/localizedlinks/types.json
> Fix incorrect persistence of links

- CHANGELOG.md
- core/src/main/java/com/contentful/vault/SyncRunnable.java
- tests-integration/src/test/java/com/contentful/vaultintegration/LocalizedLinksTest.java
- tests-integration/src/test/java/com/contentful/vaultintegration/lib/localizedlinks/Container.java
- tests-integration/src/test/resources/localizedlinks/initial.json
- tests-integration/src/test/resources/localizedlinks/types.json
> Non-localized arrays of links resolution fix

- CHANGELOG.md
- README.md
- pom.xml
- tests-integration/src/test/java/com/contentful/vaultintegration/BaseTest.java
- tests-integration/src/test/java/com/contentful/vaultintegration/SyncBase.java
- tests-integration/src/test/java/com/contentful/vaultintegration/SyncPreviewTest.java
- tests-integration/src/test/java/com/contentful/vaultintegration/SyncTest.java
This will include the possibility to do initial sync in preview. Please be advised that it will always do an initial sync in preview ...
> Updating contentful.java sdk to 7.2.0

- README.md
Found some typos in sample code in the readme
> Removed some semicolons from the sample code

- README.md
Added 2 query examples. 
Can save few hours of investigations for those who don't work with SQLite often.
> Added 2 query examples

- .mvn/wrapper/maven-wrapper.properties
- CHANGELOG.md
- README.md
- compiler/pom.xml
- core/pom.xml
- core/src/main/java/com/contentful/vault/VaultDatabaseExporter.java
- last-module/pom.xml
- pom.xml
- tests-integration/pom.xml
- tests-integration/src/test/java/com/contentful/vaultintegration/DatabaseCopyTest.java
- tests-integration/src/test/java/com/contentful/vaultintegration/SyncTest.java
- tests-integration/src/test/resources/assets/initial.json
- tests-integration/src/test/resources/assets/space.json
- tests-integration/src/test/resources/assets/types.json
> Add export utility class

- CHANGELOG.md
- README.md
- core/src/main/java/com/contentful/vault/VaultDatabaseExporter.java
- tests-integration/src/test/java/com/contentful/vaultintegration/DatabaseCopyTest.java
This should fix the issue https://github.com/contentful/vault/issues/159
> Add env var to the SyncConfig in VaultDatabaseExporter
